import type { Agent, Action, Incident, RoutingRule, ServiceOwnership, Metrics, TimelineEvent } from '@/types';

// Helper to generate recent dates
const minutesAgo = (mins: number) => new Date(Date.now() - mins * 60 * 1000);
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000);

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'CodePilot',
    type: 'code_assistant',
    status: 'active',
    actionsToday: 47,
    lastAction: minutesAgo(2),
    owner: 'Platform Team',
  },
  {
    id: 'agent-2',
    name: 'DeployBot',
    type: 'devops',
    status: 'active',
    actionsToday: 12,
    lastAction: minutesAgo(15),
    owner: 'Infrastructure',
  },
  {
    id: 'agent-3',
    name: 'DataSync',
    type: 'data_pipeline',
    status: 'active',
    actionsToday: 156,
    lastAction: minutesAgo(1),
    owner: 'Data Team',
  },
  {
    id: 'agent-4',
    name: 'SecurityGuard',
    type: 'security',
    status: 'paused',
    actionsToday: 8,
    lastAction: hoursAgo(2),
    owner: 'Security Team',
  },
  {
    id: 'agent-5',
    name: 'SupportBot',
    type: 'support',
    status: 'active',
    actionsToday: 234,
    lastAction: minutesAgo(0),
    owner: 'Customer Success',
  },
];

export const mockActions: Action[] = [
  {
    id: 'action-1',
    agentId: 'agent-3',
    agentName: 'DataSync',
    type: 'database_write',
    description: 'Batch update user analytics',
    target: 'analytics_db.user_events',
    routing: 'monitored_execute',
    status: 'completed',
    timestamp: minutesAgo(0),
    duration: 1250,
    affectedServices: ['Analytics Service', 'Dashboard'],
  },
  {
    id: 'action-2',
    agentId: 'agent-1',
    agentName: 'CodePilot',
    type: 'code_commit',
    description: 'Refactor authentication middleware',
    target: 'src/middleware/auth.ts',
    routing: 'monitored_execute',
    status: 'completed',
    timestamp: minutesAgo(2),
    duration: 450,
    affectedServices: ['Auth Service'],
  },
  {
    id: 'action-3',
    agentId: 'agent-2',
    agentName: 'DeployBot',
    type: 'deployment',
    description: 'Deploy v2.4.1 to staging',
    target: 'staging-cluster',
    routing: 'gated',
    status: 'completed',
    timestamp: minutesAgo(5),
    duration: 45000,
    affectedServices: ['API Gateway', 'User Service', 'Payment Service'],
  },
  {
    id: 'action-4',
    agentId: 'agent-5',
    agentName: 'SupportBot',
    type: 'api_call',
    description: 'Fetch customer ticket #4521',
    target: 'zendesk.api/tickets',
    routing: 'auto_execute',
    status: 'completed',
    timestamp: minutesAgo(1),
    duration: 320,
    affectedServices: ['Support Portal'],
  },
  {
    id: 'action-5',
    agentId: 'agent-1',
    agentName: 'CodePilot',
    type: 'file_modify',
    description: 'Update API endpoint documentation',
    target: 'docs/api/endpoints.md',
    routing: 'auto_execute',
    status: 'completed',
    timestamp: minutesAgo(8),
    duration: 180,
    affectedServices: ['Documentation'],
  },
  {
    id: 'action-6',
    agentId: 'agent-3',
    agentName: 'DataSync',
    type: 'database_write',
    description: 'Sync product inventory',
    target: 'inventory_db.products',
    routing: 'monitored_execute',
    status: 'executing',
    timestamp: minutesAgo(0),
    affectedServices: ['Inventory Service', 'E-commerce'],
  },
  {
    id: 'action-7',
    agentId: 'agent-2',
    agentName: 'DeployBot',
    type: 'config_change',
    description: 'Update Redis connection pool size',
    target: 'k8s/configmaps/redis-config',
    routing: 'gated',
    status: 'completed',
    timestamp: minutesAgo(20),
    duration: 2100,
    affectedServices: ['Cache Layer', 'Session Service'],
  },
  {
    id: 'action-8',
    agentId: 'agent-4',
    agentName: 'SecurityGuard',
    type: 'permission_change',
    description: 'Revoke expired API tokens',
    target: 'iam.access_tokens',
    routing: 'monitored_execute',
    status: 'completed',
    timestamp: hoursAgo(2),
    duration: 890,
    affectedServices: ['IAM Service'],
  },
];

const incidentTimeline: TimelineEvent[] = [
  {
    id: 'evt-1',
    timestamp: minutesAgo(45),
    type: 'action',
    actor: 'DataSync',
    actorType: 'agent',
    description: 'Batch update to analytics_db.user_events with malformed query',
  },
  {
    id: 'evt-2',
    timestamp: minutesAgo(44),
    type: 'alert',
    actor: 'System',
    actorType: 'system',
    description: 'Error rate spike detected in Analytics Service (5xx errors +340%)',
  },
  {
    id: 'evt-3',
    timestamp: minutesAgo(44),
    type: 'notification',
    actor: 'Asymp',
    actorType: 'system',
    description: 'Notified Sarah Chen (Data Team on-call) via Slack and PagerDuty',
  },
  {
    id: 'evt-4',
    timestamp: minutesAgo(43),
    type: 'intervention',
    actor: 'Sarah Chen',
    actorType: 'human',
    description: 'Acknowledged incident, investigating root cause',
  },
  {
    id: 'evt-5',
    timestamp: minutesAgo(40),
    type: 'note',
    actor: 'Sarah Chen',
    actorType: 'human',
    description: 'Identified malformed JOIN clause in batch query',
  },
  {
    id: 'evt-6',
    timestamp: minutesAgo(38),
    type: 'action',
    actor: 'Sarah Chen',
    actorType: 'human',
    description: 'Rolled back to previous query version via git revert',
  },
  {
    id: 'evt-7',
    timestamp: minutesAgo(35),
    type: 'recovery',
    actor: 'System',
    actorType: 'system',
    description: 'Analytics Service error rate returned to normal',
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'inc-1',
    title: 'Analytics Service degradation',
    severity: 'high',
    status: 'resolved',
    startTime: minutesAgo(45),
    endTime: minutesAgo(35),
    affectedServices: ['Analytics Service', 'Dashboard'],
    rootCause: {
      actionId: 'action-old-1',
      agentId: 'agent-3',
      agentName: 'DataSync',
      description: 'Malformed SQL query in batch update caused cascading failures',
    },
    timeline: incidentTimeline,
    responders: ['Sarah Chen'],
    tti: 60, // 1 minute to intervention
    mttr: 600, // 10 minutes to resolution
  },
  {
    id: 'inc-2',
    title: 'Elevated latency in Payment Service',
    severity: 'medium',
    status: 'monitoring',
    startTime: hoursAgo(3),
    affectedServices: ['Payment Service', 'Checkout'],
    timeline: [
      {
        id: 'evt-p1',
        timestamp: hoursAgo(3),
        type: 'alert',
        actor: 'System',
        actorType: 'system',
        description: 'P99 latency exceeded threshold (>500ms)',
      },
      {
        id: 'evt-p2',
        timestamp: hoursAgo(3),
        type: 'notification',
        actor: 'Asymp',
        actorType: 'system',
        description: 'Notified Mike Johnson (Payments on-call)',
      },
      {
        id: 'evt-p3',
        timestamp: hoursAgo(2.9),
        type: 'intervention',
        actor: 'Mike Johnson',
        actorType: 'human',
        description: 'Investigating - suspected database connection pool exhaustion',
      },
    ],
    responders: ['Mike Johnson'],
    tti: 45,
  },
];

export const mockRoutingRules: RoutingRule[] = [
  {
    id: 'rule-1',
    name: 'Production Database Writes',
    actionType: 'database_write',
    conditions: [
      { field: 'target', operator: 'contains', value: 'prod' },
    ],
    routing: 'gated',
    notifyOwners: true,
    enabled: true,
  },
  {
    id: 'rule-2',
    name: 'Staging Deployments',
    actionType: 'deployment',
    conditions: [
      { field: 'target', operator: 'contains', value: 'staging' },
    ],
    routing: 'monitored_execute',
    notifyOwners: true,
    enabled: true,
  },
  {
    id: 'rule-3',
    name: 'Production Deployments',
    actionType: 'deployment',
    conditions: [
      { field: 'target', operator: 'contains', value: 'prod' },
    ],
    routing: 'gated',
    notifyOwners: true,
    enabled: true,
  },
  {
    id: 'rule-4',
    name: 'Config Changes',
    actionType: 'config_change',
    conditions: [],
    routing: 'gated',
    notifyOwners: true,
    enabled: true,
  },
  {
    id: 'rule-5',
    name: 'Permission Changes',
    actionType: 'permission_change',
    conditions: [],
    routing: 'monitored_execute',
    notifyOwners: true,
    enabled: true,
  },
  {
    id: 'rule-6',
    name: 'Read Operations',
    actionType: 'database_read',
    conditions: [],
    routing: 'auto_execute',
    notifyOwners: false,
    enabled: true,
  },
  {
    id: 'rule-7',
    name: 'API Calls',
    actionType: 'api_call',
    conditions: [],
    routing: 'auto_execute',
    notifyOwners: false,
    enabled: true,
  },
];

export const mockOwnership: ServiceOwnership[] = [
  {
    id: 'svc-1',
    serviceName: 'Analytics Service',
    team: 'Data Team',
    primaryOwner: 'Sarah Chen',
    secondaryOwners: ['Tom Lee', 'Amy Wang'],
    onCall: 'Sarah Chen',
    slackChannel: '#data-team',
    dependencies: ['PostgreSQL', 'Redis', 'Kafka'],
  },
  {
    id: 'svc-2',
    serviceName: 'Payment Service',
    team: 'Payments',
    primaryOwner: 'Mike Johnson',
    secondaryOwners: ['Lisa Park'],
    onCall: 'Mike Johnson',
    slackChannel: '#payments',
    dependencies: ['Stripe API', 'PostgreSQL', 'Redis'],
  },
  {
    id: 'svc-3',
    serviceName: 'User Service',
    team: 'Platform',
    primaryOwner: 'Alex Kim',
    secondaryOwners: ['Jordan Smith', 'Casey Brown'],
    onCall: 'Jordan Smith',
    slackChannel: '#platform-eng',
    dependencies: ['PostgreSQL', 'Auth0', 'Redis'],
  },
  {
    id: 'svc-4',
    serviceName: 'API Gateway',
    team: 'Infrastructure',
    primaryOwner: 'Chris Davis',
    secondaryOwners: ['Pat Wilson'],
    onCall: 'Chris Davis',
    slackChannel: '#infra',
    dependencies: ['Kong', 'Redis', 'Consul'],
  },
  {
    id: 'svc-5',
    serviceName: 'Auth Service',
    team: 'Security',
    primaryOwner: 'Morgan Taylor',
    secondaryOwners: ['Jamie Garcia'],
    onCall: 'Morgan Taylor',
    slackChannel: '#security',
    dependencies: ['Auth0', 'PostgreSQL', 'Vault'],
  },
];

export const mockMetrics: Metrics = {
  totalActions24h: 1247,
  actionsByRouting: {
    auto_execute: 823,
    monitored_execute: 389,
    gated: 35,
    blocked: 0,
  },
  avgTTI: 52, // seconds
  incidentsOpen: 1,
  incidentsResolved24h: 3,
  activeAgents: 4,
  topAgents: [
    { name: 'SupportBot', actions: 234 },
    { name: 'DataSync', actions: 156 },
    { name: 'CodePilot', actions: 47 },
    { name: 'DeployBot', actions: 12 },
  ],
};

// Simulate real-time action generation
export function generateNewAction(): Action {
  const agents = mockAgents.filter(a => a.status === 'active');
  const randomAgent = agents[Math.floor(Math.random() * agents.length)];

  const actionTemplates = [
    { type: 'database_write' as const, desc: 'Update user preferences', target: 'users_db.preferences', routing: 'monitored_execute' as const },
    { type: 'api_call' as const, desc: 'Fetch external data', target: 'api.external.com/data', routing: 'auto_execute' as const },
    { type: 'file_modify' as const, desc: 'Update configuration', target: 'config/settings.json', routing: 'monitored_execute' as const },
    { type: 'code_commit' as const, desc: 'Fix bug in handler', target: 'src/handlers/main.ts', routing: 'monitored_execute' as const },
    { type: 'database_read' as const, desc: 'Query analytics data', target: 'analytics_db.events', routing: 'auto_execute' as const },
  ];

  const template = actionTemplates[Math.floor(Math.random() * actionTemplates.length)];

  return {
    id: `action-${Date.now()}`,
    agentId: randomAgent.id,
    agentName: randomAgent.name,
    type: template.type,
    description: template.desc,
    target: template.target,
    routing: template.routing,
    status: 'completed',
    timestamp: new Date(),
    duration: Math.floor(Math.random() * 2000) + 100,
    affectedServices: ['Service A'],
  };
}
